services:
  # O seu ambiente de desenvolvimento VS Code (Python e dbt)
  workspace:
    image: mcr.microsoft.com/devcontainers/python:3.11
    volumes:
      - ../:/workspaces/teste-tecnico:cached
    command: /bin/sh -c "pip install --no-cache-dir dbt-postgres && sleep infinity"
    networks:
      - data_network

  # O contêiner oficial do Apache Hop
  hop:
      image: apache/hop-web:latest
      environment:
        HOP_LOG_LEVEL: Basic
      ports:
        - "8080:8080"
      volumes:
        - ../:/workspaces/teste-tecnico
      networks:
        - data_network

  # Banco de Origem (Northwind)
  db_source:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: northwind
    ports:
      - "5432:5432"
    volumes:
      - ../northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    networks:
      - data_network

  # Banco de Destino (Data Warehouse Arruda)
  db_target:
    image: postgres:15
    environment:
      POSTGRES_USER: dw_user
      POSTGRES_PASSWORD: dw_password
      POSTGRES_DB: arruda_dw
    ports:
      - "5433:5432"
    networks:
      - data_network

networks:
  data_network: